# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='text1',
            new_name='filter_condition_Hashtag',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='text2',
            new_name='filter_condition_Key_Word',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='text3',
            new_name='filter_condition_User',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='text4',
        ),
    ]
