# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171020_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_condition_markerCoord',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
